name:                graphql
version:             0.10.0.0
synopsis:            Haskell GraphQL implementation
description:
  This package provides a rudimentary parser for the
  <https://graphql.github.io/graphql-spec/June2018/ GraphQL> language.
maintainer:          belka@caraus.de
github:              caraus-ecms/graphql
category:            Language
copyright:
- (c) 2019-2020 Eugen Wissner
- (c) 2015-2017 J. Daniel Navarro
author:
- Danny Navarro <j@dannynavarro.net>
- Matthías Páll Gissurarson <mpg@mpg.is>
- Sólrún Halla Einarsdóttir <she@mpg.is>

extra-source-files:
- CHANGELOG.md
- CONTRIBUTING.md
- LICENSE
- README.md
- docs/tutorial/tutorial.lhs

dependencies:
- aeson
- base >= 4.7 && < 5
- conduit
- containers
- exceptions
- hspec-expectations
- megaparsec
- parser-combinators
- scientific
- text
- transformers
- unordered-containers

library:
  source-dirs: src
  other-modules:
  - Language.GraphQL.Execute.Execution
  - Language.GraphQL.Execute.Subscribe
  - Language.GraphQL.Execute.Transform
  - Language.GraphQL.Type.Definition
  - Language.GraphQL.Type.Internal
  - Language.GraphQL.Validate.Rules

tests:
  tasty:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphql
    - hspec
    - hspec-megaparsec
    - QuickCheck
    - raw-strings-qq
