name:                graphql
version:             0.4.0.0
synopsis:            Haskell GraphQL implementation
description:
  This package provides a rudimentary parser for the
  <https://facebook.github.io/graphql/ GraphQL> language.
homepage:            https://github.com/jdnavarro/graphql-haskell
maintainer:          belka@caraus.de
copyright:
- 2019 Eugen Wissner
- 2015-2017 J. Daniel Navarro
category:            Web
github:              caraus-ecms/graphql
author:
- Danny Navarro <j@dannynavarro.net>
- Matthías Páll Gissurarson <mpg@mpg.is>
- Sólrún Halla Einarsdóttir <she@mpg.is>

extra-source-files:
- CHANGELOG.md
- README.md
- LICENSE
- TODO
- docs/tutorial/tutorial.lhs

data-files:
- tests/data/*.graphql
- tests/data/*.min.graphql

dependencies:
- aeson
- base >= 4.7 && < 5
- megaparsec
- text
- transformers
- unordered-containers

library:
  source-dirs: src
  dependencies:
  - scientific

tests:
  tasty:
    main: tasty.hs
    source-dirs: tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphql
    - raw-strings-qq
    - tasty
    - tasty-hunit
