name: graphql
version: 0.11.1.0
synopsis: Haskell GraphQL implementation
description:
  Haskell <https://spec.graphql.org/June2018/ GraphQL> implementation.
maintainer: belka@caraus.de
git: git://caraus.tech/pub/graphql.git
homepage: https://www.caraus.tech/projects/pub-graphql
bug-reports: https://www.caraus.tech/projects/pub-graphql/issues
category: Language
license: MPL-2.0 AND BSD-3-Clause

copyright:
- (c) 2019-2021 Eugen Wissner
- (c) 2015-2017 J. Daniel Navarro
author:
- Danny Navarro <j@dannynavarro.net>
- Matthías Páll Gissurarson <mpg@mpg.is>
- Sólrún Halla Einarsdóttir <she@mpg.is>

license-file:
- LICENSE
- LICENSE.MPL
extra-source-files:
- CHANGELOG.md
- README.md

dependencies:
- aeson
- base >= 4.7 && < 5
- conduit
- containers
- exceptions
- hspec-expectations
- megaparsec
- parser-combinators
- scientific
- text
- transformers
- unordered-containers
- vector

library:
  source-dirs: src
  other-modules:
  - Language.GraphQL.Execute.Execution
  - Language.GraphQL.Execute.Subscribe
  - Language.GraphQL.Execute.Transform
  - Language.GraphQL.Type.Definition
  - Language.GraphQL.Type.Internal
  - Language.GraphQL.Validate.Rules

tests:
  graphql-test:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphql
    - hspec
    - hspec-megaparsec
    - QuickCheck
    - raw-strings-qq
    generated-other-modules:
    - Paths_graphql
