name:                graphql
version:             0.5.0.0
synopsis:            Haskell GraphQL implementation
description:
  This package provides a rudimentary parser for the
  <https://graphql.github.io/graphql-spec/June2018/ GraphQL> language.
maintainer:          belka@caraus.de
github:              caraus-ecms/graphql
category:            Language
copyright:
- (c) 2019 Eugen Wissner
- (c) 2015-2017 J. Daniel Navarro
author:
- Danny Navarro <j@dannynavarro.net>
- Matthías Páll Gissurarson <mpg@mpg.is>
- Sólrún Halla Einarsdóttir <she@mpg.is>

extra-source-files:
- CHANGELOG.md
- README.md
- LICENSE
- docs/tutorial/tutorial.lhs

data-files:
- tests/data/*.graphql
- tests/data/*.min.graphql

dependencies:
- aeson
- base >= 4.7 && < 5
- megaparsec
- text
- transformers

library:
  source-dirs: src
  dependencies:
  - unordered-containers

tests:
  tasty:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphql
    - hspec
    - hspec-expectations
    - raw-strings-qq
